= Menggunakan WinRAR di VPS
:hp-tags: winrar, vps, linux
:published_at: 2012-12-05 13:36
Tutorial ini diimplementasikan pada VPS Linux, VPS yang saya maksud di sini adalah VPS yang hanya bisa diremote dengan `ssh` (non Desktop). Kalau VPS anda bisa diremote menggunakan software seperti VNC, saya sarankan sebaiknya anda tidak perlu melanjutkan untuk membaca tutorial ini :D.

Seperti yang diketahui bahwa software `WinRAR` bukanlah software Open Source, anda memang bisa menginstallnya misal di OS Ubuntu dengan command `sudo apt-get install rar`, akan tetapi itu hanya bisa digunakan untuk `mengekstrak` file saja. Agar anda bisa mengompressnya, anda harus membeli [lisensi](http://www.rarlab.com/shop2rarlab-whpanda.php?prod=winrar&x-source=winraronly)nya :D.

Tidak perlu khawatir, karena [di sini](http://lofian.me) anda tidak perlu membeli lisensinya :D, cukup dengan mendownload 2 file `rar` dan `unrar`.
<!--more-->

Download source rar & unrar di sini :

[http://dl.dropbox.com/u/22899587/rar](http://dl.dropbox.com/u/22899587/rar)

[http://dl.dropbox.com/u/22899587/unrar](http://dl.dropbox.com/u/22899587/unrar)

Atau download langsung di VPSnya menggunakan `wget`

```
$ wget http://dl.dropbox.com/u/22899587/rar
$ wget http://dl.dropbox.com/u/22899587/unrar
```

Untuk command compress file:

Sebelum mengcompress file, buat dulu file comment.txt untuk menambahkan comment di file rar yg nanti kita compress :D, contoh:

```	
$ ./rar a -zcomment.txt -ppassword -v50000k titanic.rar titanic.avi
```

Untuk command extract file:

```	
$ ./unrar x titanic.part1.rar -ppassword
```

__UPDATE:__

Bagi yang mempunyai VPS/Rapidleech, sekarang Rapidleech yang terbaru sudah support RAR & UnRAR bahkan ZIP dan UnZIP. Silahkan download Rapidleech yang terbaru [di sini](www.rapidleech.com/index.php/topic/14273-rapidleech-official-latest-release-svn-416/). Jika sudah didownload, extract file dan coba perhatikan pada folder `rar`, di dalam folder tersebut hanya ada 1 buah file `unrar`. Loh koq filenya cuma `unrar`? Yup, mungkin developer Rapidleech tidak mau mengambil resiko :)). Sebelum mengupload ke VPS, copy dulu file [rar](http://dl.dropbox.com/u/22899587/rar) ke folder `rar`.