= Ngetes Stompbox AMT P-1 & MXR Ten Band 
:hp-tags: Guitar, Guitar Effects Pedal, Sound, Music,

Gara-gara sering nonton video review _Stompbox_ di Youtube dan pass:q[<strike>kena racun</strike>] dapet masukan juga dari temen ane sesama gitaris, akhirnya pilihan ane jatuh pada *AMT P-1* sebagai Efek Distorsi. Efek mungil ini merupakan Efek simulasi dari Ampli legendaris *Peavey 5150*. Ane merasa cocok aja sama sound distorsinya yang pedazzz.

Jadi tepatnya hari minggu kemarin tanggal 19 Maret 2017, *Stompbox* pesenan ane akhirnya tiba dari Tangerang. Ordernya di link:http://hariharimusik.co.id[Hari Hari Musik^] via Whatsapp, sempet ragu karena belum pernah belanja di sana. Berhubung instagram link:https://www.instagram.com/hariharimusik/[@hariharimusik^] udah banyak followersnya, jadi ya langsung _hajar_ aja wkwkwk. CS-nya pun ramah, responnya juga cepet. Sorenya transfer besok paginya langsung difotoin No. Resi JNE.

Oh iya mengenai harga di link:http://hariharimusik.co.id[Hari Hari Musik^], menurut ane harganya relatif lebih murah dibandingkan dengan harga di _Jual Beli Online_ seperti Tokopedia dan Bukalapak. Kemungkinan besar ane bakal order lagi di sana wkkwkwkw.

pass:q[<blockquote class="instagram-media" data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:28.194444444444443% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/BSBpw0_BaST/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by Lofian Alvaro (@lofi_an)</a> on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2017-03-24T15:25:31+00:00">Mar 24, 2017 at 8:25am PDT</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>]

Gitar PRS CU24 --- AMT P-1 --- MXR Ten Band --- _Return_ Marshall MG100DFX.

_Keyword: testimoni hariharimusik, review efek gitar AMT P-1, review stompbox, toko musik murah, music store Indonesia, toko musik recommended seller_