= Ngetes Efek Gitar Pedal AMT P-1 & MXR Ten Band 
:hp-tags: Guitar, Guitar Effects Pedal, Sound, Music,

Tepatnya hari minggu kemarin tanggal 19 Maret 2017, *Efek Gitar Pedal* pesenan ane akhirnya tiba dari Tangerang. Ordernya di link::http://hariharimusik.co.id[Hari Hari Musik^] via Whatsapp, sempet ragu karena belum pernah belanja di sana. Berhubung instagram link::https://www.instagram.com/hariharimusik/[@hariharimusik^] udah banyak followersnya, jadi ya hajar aja wkwkwk. CS-nya ramah, responnya juga cepet. Sore transfer besok paginya langsung difotoin cetakan Resi JNE.

Soal harga silahkan bandingkan sendiri dengan _Toko Sebelah_. Pokoknya puas deh order di link::http://hariharimusik.co.id[Hari Hari Musik^] ^^.

Berikut link::https://www.instagram.com/p/BSBpw0_BaST/[video Efek Gitar Pedal AMT P-1^] yang dimix sama MXR Ten Band punya temen ane, Gitar yang digunakan *PRS CU24* dan untuk Amplinya menggunakan Ampli *Marshall MG100 DFX*. Untuk output dari Efek ane colokin ke _Return_ Marshall.