= Ngetes Efek Gitar Pedal AMT P-1 & MXR Ten Band 
:hp-tags: Guitar, Guitar Effects Pedal, Sound, Music,

Gara-gara sering nonton video review _Efek Gitar Pedal_ di Youtube dan -kena racun- dapet masukan juga dari temen ane sesama gitaris, akhirnya pilihan ane jatuh pada *AMT P-1* sebagai Efek Distorsi. Efek mungil ini merupakan Efek simulasi dari Ampli legendaris Peavey 5150. Ane merasa cocok aja sama sound distorsinya yang pedazzz.

Jadi tepatnya hari minggu kemarin tanggal 19 Maret 2017, *Efek Gitar Pedal* pesenan ane akhirnya tiba dari Tangerang ke Kudus. Ordernya di link:http://hariharimusik.co.id[Hari Hari Musik^] via Whatsapp, sempet ragu karena belum pernah belanja di sana. Berhubung instagram link:https://www.instagram.com/hariharimusik/[@hariharimusik^] udah banyak followersnya, jadi ya langsung hajar aja wkwkwk. CS-nya pun ramah, responnya juga cepet. Sorenya transfer besok paginya langsung difotoin No. Resi JNE.

Oh iya mengenai harga di link:http://hariharimusik.co.id[Hari Hari Musik^], menurut ane harganya relatif lebih murah dibandingkan dengan harga di _Jual Beli Online_ seperti Tokopedia dan Bukalapak. Kemungkinan besar ane bakal order lagi di sana wkkwkwkw.

link:https://www.instagram.com/p/BSBpw0_BaST/[Video AMT P-1 + MXR Ten Band^]

Gitar PRS CU24 --- AMT P-1 --- MXR Ten Band --- _Return_ Marshall MG100DFX.