= Pengalaman Beli dan Rental Film di iTunes
:hp-tags: Film, Movie, iTunes, 

Setiap minggunya iTunes Store selalu merilis 1 film dengan harga spesial atau *MOVIE OF THE WEEK*. Contohnya dalam minggu ini (Akhir April 2018), iTunes menambahkan Film Gifted ke dalam list *MOVIE OF THE WEEK* dengan harga Rp 29.000 dan asyiknya lagi sudah ada subtitle Indonesianya.

Tanpa berpikir panjang Film Gifted yang dibintangi Chris Evans ini langsung saya beli. Nah tetapi anehnya, ternyata kualitas subtitle Indonesianya sangatlah mengecewakan. Waktu itu lagi nonton bareng sama istri, baru menit ke 30-an film langsung saya stop karena dibingungkan dengan bahasa terjemahan yang menurut saya sangat aneh dan susah untuk dimengerti.

Akhirnya saya mengunduh subtitlenya di Subscene dan ternyata kualitas terjemahannya jauh lebih bagus ketimbang subtitle dari iTunesnya.... Boom!!! Tidak hanya film Gifted saja, waktu itu saya juga pernah nge-Rental film The Goonies, kualitas subtitlenya pun sama saja -_-. Meski demikian, masih banyak juga koq film-film di iTunes yang kualitas subtitlenya bagus, contohnya film The 5th Wave yang saya beli beberapa waktu yang lalu.