= Pengalaman Beli dan Rental Film di iTunes
:hp-tags: Film, Movie, iTunes, 

Setiap minggunya iTunes Store selalu merilis 1 film dengan harga spesial atau *MOVIE OF THE WEEK*. Contohnya dalam minggu ini (Akhir April 2018), iTunes menambahkan Film Gifted ke dalam list *MOVIE OF THE WEEK* dengan harga Rp 29.000 dan asyiknya lagi sudah ada subtitle Indonesianya.

Tanpa berpikir panjang Film Gifted yang dibintangi Chris Evans ini langsung saya beli. Namun anehnya, ternyata kualitas subtitle Bahasa Indonesianya sungguh membuat saya kecewa. Saat ditonton di menit 30-an film langsung saya stop karena dibingungkan dengan bahasa terjemahan yang menurut saya sangat aneh dan kalimatnya sulit untuk dimengerti.

_Terus gimana? Nggak jadi nonton donk?_ Ya jadi donk. Akhirnya download subtitlenya di Subscene kemudian film di iTunes didownload dulu dan diremove DRM-nya pake software DVDFab, fungsinya agar film iTunes bisa ditonton dengan menggunakan subtitle external. Untuk kualitas terjemahan dari subscene ternyata jauh lebih bagus dari subtitle iTunes.... Tidak hanya film Gifted saja, waktu itu saya pernah nge-Rental film The Goonies, kualitas subtitlenya pun ternyata sama saja -_-. Meski demikian, masih banyak juga koq film-film di iTunes yang kualitas terjemahan subtitlenya bagus, contohnya film The 5th Wave yang saya beli beberapa waktu yang lalu.